#!/usr/bin/env python3
import os
import sys
import logging
import argparse
import platform
from vampire.build import PythonBuild
from vampire.packages import PythonPackages
from vampire.versions import available_versions


logging.basicConfig(
    format='[%(levelname)s] %(message)s'
)
logger = logging.getLogger('vampire')
logger.setLevel(logging.INFO)


def version():
    """
    Print the version and exit.
    """
    print('Vampire %s\n' % 0.1)
    sys.exit(0)


def main():
    """
    Parse arguments and execute.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('--version', help='Specify the Python version', default=platform.python_version())
    parser.add_argument('--target', help='Specify the target directory',
                        default=os.path.join(os.path.expanduser('~'), 'python'))
    parser.add_argument('--host', help='Specify the target host', default='localhost')
    parser.add_argument('--packages', help='Specify required packages', nargs='+')
    parser.add_argument('--requirements', help='Specify pip requirements file')
    parser.add_argument('--DEBUG', help='Switch logger to debug output', action='store_true', default=False)
    parser.add_argument('--VERSION', help='Print Vampire version and exit', action='store_true', default=False)
    parser.add_argument('--list', help='Print available minor Python branches', action='store_true', default=False)
    parser.add_argument('--listall', help='Print all known available Python versions', action='store_true', default=False)
    args = parser.parse_args()

    if args.VERSION:
        version()

    if args.DEBUG:
        logger.setLevel(logging.DEBUG)

    if args.list:
        print("Available Python versions:")
        print("\n".join(available_versions(recent=True)))
        sys.exit(0)

    if args.listall:
        print("All known and available Python versions:")
        print("\n".join(available_versions()))
        sys.exit(0)

    logger.info('Starting Vampire.')
    build = PythonBuild(
        args.version,
        args.target,
        args.host
    )
    build()

    packages = PythonPackages(
        build,
        packages=args.packages,
        requirements=args.requirements
    )
    packages()
    logger.info('Finished.')


if __name__ == '__main__':
    main()
